name = "apiful"
compatibility_date = "2025-06-01"
workers_dev = false

routes = [
  { pattern = "apiful.byjohann.dev", custom_domain = true }
]

[assets]
directory = "./docs/.vitepress/dist/"
not_found_handling = "404-page"
